using System.Text.Json;
using WcgWeb.Models;
namespace WcgWeb.Services;

// Opponent pools per ranked tier. Data is generated by tools/RankedDecks/build_ranked_decks.py.
// The picked deck (including any variant swaps) is stored in the match snapshot, so replays never re-pick.
public sealed partial class RankedDecks
{
    public record Variant(string Name, List<string> Out, List<string> In);
    public record Entry(int Tier, Deck Deck, string Archetype = "", List<Variant>? Variants = null);
    public const int MaxVariantsPerMatch = 2;
    public IReadOnlyList<Entry> All { get; }
    private readonly Func<string, CardDefinition?> getCard;
    public RankedDecks(CardDatabase cards, string json)
    {
        getCard = cards.GetCard;
        All = JsonSerializer.Deserialize<List<Entry>>(json) ?? throw new InvalidDataException("天梯牌組資料為空。");
        if (All.Select(e => e.Deck.Id).Distinct().Count() != All.Count) throw new InvalidDataException("天梯牌組 ID 重複。");
        foreach (var entry in All)
        {
            if (entry.Tier is < 0 or > 5) throw new InvalidDataException("天梯牌位不正確：" + entry.Deck.Name);
            if (!IsLegal(entry.Deck, out var error)) throw new InvalidDataException("天梯牌組不合法：" + entry.Deck.Name + " " + error);
            foreach (var variant in entry.Variants ?? [])
                if (Apply(entry.Deck, variant) is not { } changed || !IsLegal(changed, out _))
                    throw new InvalidDataException($"天梯牌組微調不合法：{entry.Deck.Name} / {variant.Name}");
        }
        if (Enumerable.Range(0, 6).Any(t => All.Count(e => e.Tier == t) < 5)) throw new InvalidDataException("各牌位須至少五套對手牌組。");
    }
    // Deck.Validate covers size, copies and factions; ranked data also keeps the off-color limit from 規則.md.
    public bool IsLegal(Deck deck, out string? error)
    {
        if (!deck.IsValid(getCard, out error)) return false;
        if (deck.GetColorCounts(getCard).OffColor > Deck.MaxOffColorCards) { error = $"混色超過 {Deck.MaxOffColorCards} 張"; return false; }
        return true;
    }
    public IReadOnlyList<Entry> Pool(int tier) => All.Where(e => e.Tier == tier).ToArray();
    public Deck Pick(int tier, Random random, string? avoidDeckId = null)
    {
        var pool = Pool(tier);
        // Do not face the same archetype twice in a row when the tier offers alternatives.
        var fresh = pool.Where(e => !SameArchetype(e.Deck.Id, avoidDeckId)).ToArray();
        var candidates = fresh.Length > 0 ? fresh : pool;
        var entry = candidates[random.Next(candidates.Count)];
        var deck = DeckService.Copy(entry.Deck);
        var variants = (entry.Variants ?? []).OrderBy(_ => random.Next()).Take(random.Next(MaxVariantsPerMatch + 1));
        foreach (var variant in variants)
            if (Apply(deck, variant) is { } changed && IsLegal(changed, out _)) deck = changed;
        return deck;
    }
    private static bool SameArchetype(string id, string? other)
    {
        if (string.IsNullOrEmpty(other)) return false;
        static string Key(string value) { var parts = value.Split('-', 3); return parts.Length == 3 && parts[0] == "RANKED" ? parts[2] : value; }
        return Key(id) == Key(other);
    }
    public static Deck? Apply(Deck deck, Variant variant)
    {
        var copy = DeckService.Copy(deck);
        foreach (var id in variant.Out) if (!copy.CardIds.Remove(CardIdentifier.Canonical(id))) return null;
        copy.CardIds.AddRange(variant.In.Select(CardIdentifier.Canonical));
        return copy;
    }
    public string Summary(int tier)
    {
        var pool = Pool(tier);
        var styles = pool.GroupBy(e => e.Archetype == "" ? "其他" : e.Archetype).OrderByDescending(g => g.Count()).ThenBy(g => g.Key, StringComparer.Ordinal)
            .Select(g => $"{g.Key} {g.Count()}");
        return $"{pool.Count} 副對手（{string.Join("、", styles)}）";
    }
    public static string Strategy(int tier) => tier switch
    {
        0 => "新手電腦：常隨機出牌、亂選目標，半數看漏斬殺；入門牌表",
        1 => "基礎電腦：照怪物優先順序出牌，偶爾失誤；基礎牌表",
        2 => "進階電腦：評估交換與目標、會用直傷斬殺；雙色流派登場",
        3 => "老練電腦：注意反撲、優先鋪場；牌表更完整",
        4 => "高手電腦：聰明填能量、兩步攻擊規劃；雙色控制登場",
        _ => "大師電腦：幾乎不失誤、三步攻擊規劃、先解嘲諷再斬殺；完整牌表",
    } + "；每場隨機微調 0～2 組卡牌";
}
